### ISSUE TITLE
[ FEATURE ] Adicionar container Portainer ao projeto

### ISSUE THREAD

**Issue by CeruttiMaicon** [Zoren-Software/VoleiClub#17]
Adicionar ao docker-compose.yml

```
    portainer:
        image: portainer/portainer-ce:latest
        container_name: voleiclub.portainer
        restart: unless-stopped
        security_opt:
        - no-new-privileges:true
        volumes:
        - /etc/localtime:/etc/localtime:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./portainer-data:/data
        ports:
        - 9000:9000
```
